[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [
    { name = "Kabir", email = "kabirsinha2111@gmail.com" }
]

requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn (>=23.0.0,<24.0.0)",
]
